### ISSUE TITLE
Gutter Decoration 

### ISSUE THREAD

**Issue by Zelacks** [callum-ramage/path-of-exile-item-filter#10]
Fresh install, with the latest versions of the dependencies, it seems that the gutter decarations for the colors and playing the sound have stopped working.

http://i.imgur.com/7wTcfXt.png

**Comment by GlenCFL** [comment]
I'll look into this.

**Comment by GlenCFL** [comment]
The linter was updated and changed the name of its gutter, which we use for our own decorations right now. We'll stop using their gutter soon, but for now this solution should work.

**Comment by Zelacks** [comment]
That seemed like the case, its working now though.
Thank you so much for your work! Your atom package is pretty much the best thing to use to make filters!
