### ISSUE TITLE
Linter Integration

### ISSUE THREAD

**Issue by GlenCFL** [callum-ramage/path-of-exile-item-filter#3]
I've been working on a [Linter](https://github.com/steelbrain/linter) for the package in my free time. The problem that I ran into was that the item data needed to be decoupled from the autocompletion code in order to use it in both the linter provider and autocompletion provider. With the Linter nearly completed, the autocompletion provider now needs to be modified in order to make use of the new JSON data, but this brings us to a crossroads.

The linter is written in TypeScript, so the question is whether or not I should take this opportunity to just port everything to it. All of the code being TypeScript vs. some components being written in CoffeeScript and others in TypeScript.

Worth noting that I chose TypeScript for the linter because of the [atom-typescript](https://github.com/TypeStrong/atom-typescript) package.

**Comment by callum-ramage** [comment]
Sorry, I didn't get an email about you creating this issue for some reason. A Linter sounds like a great feature. Can I see the code so far? I'm pretty happy to have it all ported but I want to see what it's like first. The atom-typescript package does look like it's worth using. I'm happy to help but I'm in another country on holiday at the moment.

**Comment by GlenCFL** [comment]
I decided just to rewrite the linter in CoffeeScript. I'll update this or just create a pull request once the rewrite is complete.

The autocompletion provider will still need to be rewritten to create its snippets from shared JSON data files at runtime, but that can wait until the linter is merged.

**Comment by callum-ramage** [comment]
I can't wait to see it.

**Comment by GlenCFL** [comment]
[grammars/poe.cson](https://github.com/GlenCFL/path-of-exile-item-filter/blob/c36e7e73e8c26795202f9d00bdc9efe4617b5e7e/grammars/poe.cson)
[styles/poe.less](https://github.com/GlenCFL/path-of-exile-item-filter/blob/c36e7e73e8c26795202f9d00bdc9efe4617b5e7e/styles/poe.less)

Are you fine with this rewrite of the grammar? The rewrite initially began with the goal to hopefully using the data from it to enable partial updates in the linter, but that didn't pan out. Partial updates will still be supported, but in another way.

The updated grammar is oriented more towards highlighting valid tokens. The names have all changed to what is more typical in Atom, which gives us automatic syntax theme support. The linter will cover the cases where the user has used an invalid format or given invalid values, so we don't need to care about that here anymore.

**Comment by callum-ramage** [comment]
Yeah that looks good. It's much clearer than my version.

**Comment by GlenCFL** [comment]
This probably wont be merged for Path of Exile 2.5, which we'll have patch notes for today, but I'm keeping relevant changes synchronized.

I detoured back into TypeScript. The original problem was that the public type definitions for the Atom API were both out of date and incomplete, with pretty much all of the new event-driven stuff being missing, but I've been working on just outright replacing them. My [repository](https://github.com/GlenCFL/path-of-exile-item-filter/tree/48de243b38f2b2fc1f5ef4736386300455acf137) has an example as to how some of the TypeScript code would look.

The Linter itself is incomplete and will be stitched together from both the CoffeeScript source and the old TypeScript source. Right now it's just a skeleton that logs events.
