### ISSUE TITLE
Where do you get all this data?

### ISSUE THREAD

**Issue by O4epegb** [callum-ramage/path-of-exile-item-filter#5]
Hey, guys!
I wanted to make poe.filter syntax highlight for Atom just for fun and practice, but then discovered that you already made this great plugin!
My question is, where do you get all the data for completion and such? And are you typing it manually? That is such a massive amount of info, almost 2k lines.
Great work, nevertheless!

**Comment by callum-ramage** [comment]
I copy/pasted a lot of it off the wiki and the main site and used fine/replace to reformat it. I still typed up quite a lot of it. No sure how Glen did the divination card part.

If you want to play around, you can use the stuff out of completion.coffee
